<?php
    $lang['number']   = 'Фактура №';
    $lang['date']     = 'Издадена на';
    $lang['time']     = 'Издадена към';
    $lang['due']      = 'Краен срок';
    $lang['to']       = 'Купувач';
    $lang['from']     = 'Продавач';
    $lang['product']  = 'Артикул';
    $lang['qty']      = 'Брой';
    $lang['price']    = 'Цена';
    $lang['discount'] = 'Отстъпка';
    $lang['vat']      = 'ДДС';
    $lang['total']    = 'Общо';
    $lang['page']     = 'Страница';
    $lang['page_of']  = 'от';
